POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "HadrianOOP",
  "number": "787528528"
}

###
GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/670eef3f985dfa2467cf76
###
DELETE  http://localhost:3001/api/persons/670eef3f985dfa2467cf76
###
PUT http://localhost:3001/api/persons/670f0884277e9130b946b17f
Content-Type: application/json

{
  "name": "Mudaa",
  "number": "123-8932852"
}
###
GET http://localhost:3001/info